language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install: pip install tox-travis
script: tox
notifications:
  email: false
deploy:
  provider: pypi
  user: __token__
  password:
    secure: twUSrEK9RghQuAPECAtEwz0ztgMKwrsBvf5/xnFFFz6lF1qQjXzRnFxgL5mIWHeAcR1GjUWosXV6O46wHGQzT5iipC7xE6yXSe4kxnyr8worEZE2c6UfIfDqbByjjo2GCOe6HMuW/EdegF2JvkS0Coj14jE74/N/kolwLnqU0rAdsg7HK8ZTxgvjOTVOc1g+bok24d87TQYYn4RLKBzMkLoiqaDUO5t4GG/GfNYVPtApHPi2h/D+SoTaJ5zFCbVm7qhBKHjVe2uhxVJbS/LLAJLicly4vu+MN2guBXZNvYtSxX1u8+HZtu24PjpxUN5jw4phTrLFMLv8T4CXWMsPmptxg48NqucQG4N+w4D+3ZIq4xvRFAkOHxUij4cAHPY6Y9z7xsk+4VkljkCq6/e4+dNTq63E/Hq6cvNyMz0gRyaEiTZV7rpH7UMF4mQ7HRzUjNqDGSR/d78zjH8LwDzy/NA1JrDMmC1XJgr2tN1fc5LlnrVrYO55uq3uoy9aZuGA1tN4iBRN6Vxhfa8jBbKUXF7YerSPfoVSe+A9Z7/DP1KAeyZDR4ZIt5A6glrj1KdQqfpMiM1uWCPK0I5cZFQiY99sUX46wD1WYu9po6KbrEluXVRySKa5P2ry7YhsYiW7Fer5K+Hg92M2xzZp+mY/pnaphXYYr/o/piJaxYxqCcQ=
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
